### ISSUE TITLE
Home / Away / Night / Off Modes - Whats the difference

### ISSUE THREAD

**Issue by coalfield** [jak1502/homebridge-yalesmarthomealarm#2]
As far as I know the Yale alarms only support Home / Away / Off, so what is the difference with Night mode on the app config?  Is it possible to reduce this to and remove Night presuming its the same as Home mode?

Also is there any disadvantage to decreasing the poll time for this as I am noticing this is often out of sync?

**Comment by jak1502** [comment]
Yale does only support off/home/away but HomeKit includes the night mode too, there is no way to disable this as far as I am aware. I have set it so night and home mode part arm the system, so it doesn’t matter which one you choose. 

Reducing the polling time shouldn’t cause any issues. It just calls the Yale API every time it polls so it just adds more network traffic. The minimum is 5000, this equates to checking every 5 seconds.
