### ISSUE TITLE
Not working when assigned to a Hue Switch via HomeHub

### ISSUE THREAD

**Issue by coalfield** [jak1502/homebridge-yalesmarthomealarm#3]
This is all working great for me, however having an issue where I am trying to assign arm or disarm to a Hue dimmer button.  I.e. Hue dimmer button 4 action / Yale alarm off.

When I test the scene it works fine.  However when I use the button nothing happens.

This is an odd one as it used to work, yet now I get nothing.  I have done a clean install still the same.  Also I know the button is working becuase if I add a light to the action I can change this, but it ignores the Yale alarm change.

Lost on this one I have spent some time trying to fix.  Any ideas welcome!

**Comment by jak1502** [comment]
how are you trying to set up the automation? Is it within the home app? I don’t have the Hue to test but it does sound like a homekit/bridge issue. 

I have automations working fine here based on time but not tired buttons/events.
