### ISSUE TITLE
Will this work??

### ISSUE THREAD

**Issue by xkyle22x** [jak1502/homebridge-yalesmarthomealarm#5]
Hi I want to purchase a Yale alarm but I'm in Australia and the alarm we have here I'm not sure if it will work. 
It is 433mhz frequency 
The part number is B-HSA6500-AU
The APP for Yale is "Yale smart living home" 
Would you be able to tell me from this link if it will?? 
Thanks in advance. 

https://www.bunnings.com.au/yale-easy-fit-wireless-alarm-kit_p0079199

**Comment by jak1502** [comment]
I think it should work still. Is the app that it uses this?

https://apps.apple.com/gb/app/yale-smart-living-home/id1110301671

**Comment by xkyle22x** [comment]
Yes that is the same app.

**Comment by jak1502** [comment]
It should work fine then.
